#!/usr/bin/env php
<?php
/**
 * Aurxy - Http filter and proxy server.
 *
 * @author Panlatent <panlatent@gmail.com>
 */

use Aurxy\Console\Application;
use Aurxy\Console\Command\RunCommand;

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/src/Aurxy.php';

$app = new Application(Aurxy::NAME, Aurxy::VERSION);
$app->add(new RunCommand());
$app->setDefaultCommand('run');
$app->run();
